import { Preset } from '../types';

// prettier-ignore
export const CLOCK: Preset = {
  params: { rows: 20, cols: 20 },
  grid: [
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false],
    [false, false, false, false, true, true, false, true, false, false, false, false, true, false, false, false, false, false, false, false],
    [false, false, false, false, true, true, false, true, false, true, true, false, true, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, true, false, false, false, true, true, false, true, true, false, false, false, false],
    [false, false, false, false, false, false, false, true, false, false, false, false, true, false, true, true, false, false, false, false],
    [false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],
};

// prettier-ignore
export const SHIP_44P5H2V0: Preset = {
  params: { rows: 21, cols: 21 },
  grid: [
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, false, false, false, false, false, false, false, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, false, true, false, false, false, false, false, true, false, true, false, false, false, false, false],
    [false, false, false, false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, false, false, false],
    [false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false],
    [false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false],
    [false, false, false, true, true, false, false, false, true, false, false, false, true, false, false, false, true, true, false, false, false],
    [false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false],
    [false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false],
  ],
};

// prettier-ignore
export const HANGAR: Preset = {
  params: { rows: 21, cols: 21 },
  grid: [
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
  ],
};

// prettier-ignore
export const PULSAR: Preset = {
  params: { rows: 21, cols: 21 },
  grid: [
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, false, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, false, false, false],
    [false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],
};
// prettier-ignore
export const PLANER_GUN: Preset = {
  params: { rows: 29, cols: 43 },
  grid: [
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false, true, true, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, false, true, true, false, false, false],
    [false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false],
    [false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false, false, true, true, true, true, false, false, false, false, true, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],
};
